version: '3'
services:
    nginx:
        container_name: 'nginx'
        image: 'jwilder/nginx-proxy'
        restart: 'always'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - './nginx/html/:/usr/share/nginx/html/'
            - './nginx/conf.d/:/etc/nginx/conf.d/'
            - './nginx/certs/:/etc/nginx/certs/:ro'
            - './nginx/vhost.d/:/etc/nginx/vhost.d/'
            - './nginx/dhparam/:/etc/nginx/dhparam/'
            - './domjudge/nginx-domjudge.conf:/etc/nginx/conf.d/domjudge.conf'
        environment:
            ENABLE_IPV6: 'true'
            DEFAULT_HOST: 'domjudge.thalia.nu'

    letsencrypt:
        image: 'jrcs/letsencrypt-nginx-proxy-companion'
        restart: 'always'
        depends_on:
            - 'nginx'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './nginx/html/:/usr/share/nginx/html/'
            - './nginx/conf.d/:/etc/nginx/conf.d/'
            - './nginx/vhost.d/:/etc/nginx/vhost.d/'
            - './nginx/dhparam/:/etc/nginx/dhparam/'
            - './nginx/certs/:/etc/nginx/certs/'
            - './domjudge/nginx-domjudge.conf:/etc/nginx/conf.d/domjudge.conf'
        environment:
            NGINX_PROXY_CONTAINER: 'nginx'
            DEFAULT_EMAIL: 'bapc@thalia.nu'

    domjudge:
        #image: 'domjudge/domserver'
        build: ./domjudge
        restart: always
        links:
            - "dj-mariadb:mariadb"
        environment:
            VIRTUAL_HOST: 'domjudge.thalia.nu,contest.thalia.nu'
            LETSENCRYPT_HOST: 'domjudge.thalia.nu,contest.thalia.nu'
            LETSENCRYPT_EMAIL: 'bapc@thalia.nu'
            DJ_DB_INSTALL_BARE: '1'
            TRUSTED_PROXIES: '172.18.0.0/24'
        env_file:
            - domjudge/domserver.env
            - domjudge/database.env
        volumes:
            - './domjudge/domjudge-images/:/opt/domjudge/domserver/webapp/public/images/'
            - './domjudge/custom-css/:/opt/domjudge/domserver/webapp/public/css/custom/'
            - './domjudge/custom-js/:/opt/domjudge/domserver/webapp/public/js/custom/'
            - './domjudge/logs/:/opt/domjudge/domserver/webapp/public/log'
            - './printjobs:/printjobs'

    dj-mariadb:
        image: mariadb
        restart: always
        ports:
            - '13306:3306'
        env_file:
            - domjudge/database.env
        volumes:
            - './domjudge/db_conf:/etc/mysql/conf.d'

    cds:
        image: 'icpctools/cds:2.4.727'
        restart: always
        env_file:
            - cds/cds.env
        environment:
            VIRTUAL_HOST: 'contestdata.thalia.nu'
            VIRTUAL_PORT: 8080
            LETSENCRYPT_HOST: 'contestdata.thalia.nu'
            LETSENCRYPT_EMAIL: 'bapc@thalia.nu'
        volumes:
            - './cds/contest-data:/contest'
            - './cds/present:/opt/wlp/usr/servers/cds/config/present'
            - './cds/cdsConfig.xml:/opt/wlp/usr/servers/cds/config/cdsConfig.xml'

    cups:
        build: ./cups
        restart: always
        hostname: contest.thalia.nu
        ports:
            - '631:631'
        volumes:
            - './cups/cups-config/:/etc/cups/'
            - './nginx/certs/:/etc/cups/ssl/'
            - '/var/run/dbus:/var/run/dbus'
        env_file:
            - cups/cups.env
