version: '3'
services:
    nginx:
        container_name: 'nginx'
        image: 'jwilder/nginx-proxy'
        restart: 'always'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
            - './nginx/html/:/usr/share/nginx/html/'
            - './nginx/conf.d/:/etc/nginx/conf.d/'
            - './nginx/certs/:/etc/nginx/certs/:ro'
            - './nginx/vhost.d/:/etc/nginx/vhost.d/'
            - './nginx/dhparam/:/etc/nginx/dhparam/'
            - './domserver/nginx-domjudge.conf:/etc/nginx/conf.d/domjudge.conf'
        environment:
            ENABLE_IPV6: 'true'
            DEFAULT_HOST: 'domjudge.thalia.nu'

    letsencrypt:
        image: 'jrcs/letsencrypt-nginx-proxy-companion'
        restart: 'always'
        depends_on:
            - 'nginx'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './nginx/html/:/usr/share/nginx/html/'
            - './nginx/conf.d/:/etc/nginx/conf.d/'
            - './nginx/vhost.d/:/etc/nginx/vhost.d/'
            - './nginx/dhparam/:/etc/nginx/dhparam/'
            - './nginx/certs/:/etc/nginx/certs/'
            - './nginx-domjudge.conf:/etc/nginx/conf.d/domjudge.conf'
        environment:
            NGINX_PROXY_CONTAINER: 'nginx'
            DEFAULT_EMAIL: 'bapc@thalia.nu'
    
    domjudge:
        build: ./domserver
        restart: always
        links:
            - "dj-mariadb:mariadb"
        environment:
            VIRTUAL_HOST: 'domjudge.thalia.nu,contest.thalia.nu,bapc-domtest.technicie.nl'
            LETSENCRYPT_HOST: 'domjudge.thalia.nu,contest.thalia.nu,bapc-domtest.technicie.nl'
            LETSENCRYPT_EMAIL: 'bapc@thalia.nu'
        env_file:
            - domserver.env
            - database.env
        volumes:
            - './domserver/domjudge-images/:/opt/domjudge/domserver/webapp/public/images/'

    dj-mariadb:
        image: mariadb
        restart: always
        ports:
            - '13306:3306'
        env_file:
            - database.env
        volumes:
            - './domserver/db_conf:/etc/mysql/conf.d'

    cds:
        build: ./cds
        restart: always
        env_file:
            - cds.env
        environment:
            VIRTUAL_HOST: 'contestdata.thalia.nu'
            LETSENCRYPT_HOST: 'contestdata.thalia.nu'
            LETSENCRYPT_EMAIL: 'bapc@thalia.nu'
        volumes:
            - './cdsConfig.xml:/opt/wlp/usr/servers/cds/config/cdsConfig.xml'
            - './contest-data:/contest-data'

    cups:
        build: ./cups
        restart: always
        hostname: bapc-domtest.technicie.nl
        ports:
            - '631:631'
        volumes:
            - './cups/cups-config/:/etc/cups/'
            - './nginx/certs/:/etc/cups/ssl/'
            - '/var/run/dbus:/var/run/dbus'
        env_file:
            - cups.env

